[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "yarn next build"
  publish = ".next"
  
[build.environment]
  NEXT_CACHE_DIR = ".next/cache"

[[plugins]]
  package = "@netlify/plugin-nextjs"
